create table alternative (id bigint generated by default as identity, alternative_type integer not null, image varchar(255), rate integer, selected boolean, title varchar(255) not null, survey_id bigint not null, primary key (id));
create table survey (id bigint generated by default as identity, title varchar(255), primary key (id));
create table survey_altrernatives (survey_id bigint not null, altrernatives_id bigint not null, primary key (survey_id, altrernatives_id));
alter table survey_altrernatives add constraint UK_7xh49g55q14aurffqwv7ywde7 unique (altrernatives_id);
alter table alternative add constraint FK8c2gcijcn3k9x0qq2ho1hcwlu foreign key (survey_id) references survey;
alter table survey_altrernatives add constraint FK1kxj1ctjjirdtl36rl914ni9j foreign key (altrernatives_id) references alternative;
alter table survey_altrernatives add constraint FKqvhdh4mqe3v39hejuw441a1mi foreign key (survey_id) references survey;
